### ISSUE TITLE
History module only displaying credit transactions on windows 10

### ISSUE THREAD

**Issue by Jugalug123** [KenCorma/nexus-interface-history-module#21]
I am unable to download a CSV report in the history module on windows 10, plus the only transactions I can see are credit transactions no other transactions are displayed.
I also have time span and operation set to all.

**Comment by NealHelman** [comment]
I see CREDIT and DEBIT transactions, but no TRUST transactions.  That is also with Time Span and Operation set to All

**Comment by NealHelman** [comment]
This has been fixed with core 5.1.1rc11

**Comment by Jugalug123** [comment]
> I am unable to download a CSV report in the history module on windows 10, plus the only transactions I can see are credit transactions no other transactions are displayed. I also have time span and operation set to all.

**Comment by Jugalug123** [comment]
This issue has now been resolved
