### ISSUE TITLE
Add a more reasonable limit to the transactions API call

### ISSUE THREAD

**Issue by NealHelman** [KenCorma/nexus-interface-history-module#6]
In the app.js file, I added "limit=100000" to prevent the API call from only getting 100 transactions.  100 is an unusable number of transactions, while 100,000 is much more likely to cover a year's worth of activity or more.

Here is the function call I changed:
P("finance/list/account/transactions",{address:e.address,limit:100000});

**Comment by KenCorma** [comment]
Added this as a settings give it a try.

**Comment by NealHelman** [comment]
Updated the module, let it completely reload the transactions, then clicked the Settings gear icon.  Was presented with a blank module screen.

**Comment by KenCorma** [comment]
> Updated the module, let it completely reload the transactions, then clicked the Settings gear icon. Was presented with a blank module screen.

Forgot names are minified in production, bad form. Will put out a new version soon.

**Comment by KenCorma** [comment]
Check latest Release

**Comment by KenCorma** [comment]
I am going to close this now that version 0.8.2
